create table if not exists public.notes (id bigint generated by default as identity primary key, owner_id uuid, title text not null, content text not null, created_at timestamptz not null default now());
alter table public.notes enable row level security;
revoke all on table public.notes from anon, authenticated;
grant select on table public.notes to service_role;
insert into public.notes (title, content) values ('과제','실습용 가상 과제 기록'),('포트폴리오','실습용 가상 포트폴리오 기록'),('아침 리추얼','실습용 가상 리추얼 기록'),('훈련 행정 자료','실습용 가상 행정 기록');
